services:
  Catalog_API_DB:
    container_name: Catalog_API_DB
    restart: always
    volumes:
      - ./mongo_data:/data/db

    ports:
        - "27017:27017"
        
  Basket_API_DB:
    container_name: Basket_API_DB
    restart: always
    ports:
       - "6379:6379" 

  portainer:
    container_name: portainer
    restart: always
    ports:
       - "8080:8000"
       - "9000:9000"
    volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
       - "portainer_data:/data"


  catalog.api:
    container_name: Catalog.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - "DatabaseSettings:ConnectionString=mongodb://Catalog_API_DB:27017"
    depends_on : 
      - Catalog_API_DB
    ports:
      - "8000:8000"
  basket.api:
    container_name: Basket.API 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - "CacheSettings:ConnectionString=Basket_API_DB:6379" 
    ports:
      - "8002:8000"

