services:
  Catalog_API_DB:
    container_name: Catalog_API_DB
    restart: always
    volumes:
      - ./mongo_data:/data/db

    ports:
        - "27017:27017"

  catalog.api:
    container_name: Catalog.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - "DatabaseSettings:ConnectionString=mongodb://Catalog_API_DB:27017"
    depends_on : 
      - Catalog_API_DB
    ports:
      - "8000:8000"